# coding: utf-8

"""
    Sommerblut-Database

    Event and festival info  # noqa: E501

    OpenAPI spec version: 1.5.0
    Contact: support@xtain.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EventPriceHandling(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'enable_price_fields': 'bool',
        'show_name_in_fe': 'bool',
        'name': 'str'
    }

    attribute_map = {
        'id': 'id',
        'enable_price_fields': 'enable_price_fields',
        'show_name_in_fe': 'show_name_in_fe',
        'name': 'name'
    }

    def __init__(self, id=None, enable_price_fields=None, show_name_in_fe=None, name=None):  # noqa: E501
        """EventPriceHandling - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._enable_price_fields = None
        self._show_name_in_fe = None
        self._name = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if enable_price_fields is not None:
            self.enable_price_fields = enable_price_fields
        if show_name_in_fe is not None:
            self.show_name_in_fe = show_name_in_fe
        if name is not None:
            self.name = name

    @property
    def id(self):
        """Gets the id of this EventPriceHandling.  # noqa: E501


        :return: The id of this EventPriceHandling.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this EventPriceHandling.


        :param id: The id of this EventPriceHandling.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def enable_price_fields(self):
        """Gets the enable_price_fields of this EventPriceHandling.  # noqa: E501


        :return: The enable_price_fields of this EventPriceHandling.  # noqa: E501
        :rtype: bool
        """
        return self._enable_price_fields

    @enable_price_fields.setter
    def enable_price_fields(self, enable_price_fields):
        """Sets the enable_price_fields of this EventPriceHandling.


        :param enable_price_fields: The enable_price_fields of this EventPriceHandling.  # noqa: E501
        :type: bool
        """

        self._enable_price_fields = enable_price_fields

    @property
    def show_name_in_fe(self):
        """Gets the show_name_in_fe of this EventPriceHandling.  # noqa: E501

        Should the name be shown in Frontend instead of price fields  # noqa: E501

        :return: The show_name_in_fe of this EventPriceHandling.  # noqa: E501
        :rtype: bool
        """
        return self._show_name_in_fe

    @show_name_in_fe.setter
    def show_name_in_fe(self, show_name_in_fe):
        """Sets the show_name_in_fe of this EventPriceHandling.

        Should the name be shown in Frontend instead of price fields  # noqa: E501

        :param show_name_in_fe: The show_name_in_fe of this EventPriceHandling.  # noqa: E501
        :type: bool
        """

        self._show_name_in_fe = show_name_in_fe

    @property
    def name(self):
        """Gets the name of this EventPriceHandling.  # noqa: E501


        :return: The name of this EventPriceHandling.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this EventPriceHandling.


        :param name: The name of this EventPriceHandling.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EventPriceHandling, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EventPriceHandling):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
