# coding: utf-8

"""
    Sommerblut-Database

    Event and festival info  # noqa: E501

    OpenAPI spec version: 1.5.0
    Contact: support@xtain.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DatesInner(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'event': 'Event',
        'eventdate': 'date'
    }

    attribute_map = {
        'event': 'event',
        'eventdate': 'eventdate'
    }

    def __init__(self, event=None, eventdate=None):  # noqa: E501
        """DatesInner - a model defined in Swagger"""  # noqa: E501
        self._event = None
        self._eventdate = None
        self.discriminator = None
        if event is not None:
            self.event = event
        if eventdate is not None:
            self.eventdate = eventdate

    @property
    def event(self):
        """Gets the event of this DatesInner.  # noqa: E501


        :return: The event of this DatesInner.  # noqa: E501
        :rtype: Event
        """
        return self._event

    @event.setter
    def event(self, event):
        """Sets the event of this DatesInner.


        :param event: The event of this DatesInner.  # noqa: E501
        :type: Event
        """

        self._event = event

    @property
    def eventdate(self):
        """Gets the eventdate of this DatesInner.  # noqa: E501

        Date of event  # noqa: E501

        :return: The eventdate of this DatesInner.  # noqa: E501
        :rtype: date
        """
        return self._eventdate

    @eventdate.setter
    def eventdate(self, eventdate):
        """Sets the eventdate of this DatesInner.

        Date of event  # noqa: E501

        :param eventdate: The eventdate of this DatesInner.  # noqa: E501
        :type: date
        """

        self._eventdate = eventdate

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DatesInner, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DatesInner):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
