# coding: utf-8

"""
    Sommerblut-Database

    Event and festival info  # noqa: E501

    OpenAPI spec version: 1.5.0
    Contact: support@xtain.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sb_db
from sb_db.api.events_api import EventsApi  # noqa: E501
from sb_db.rest import ApiException


class TestEventsApi(unittest.TestCase):
    """EventsApi unit test stubs"""

    def setUp(self):
        self.api = EventsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_events(self):
        """Test case for get_all_events

        get all events  # noqa: E501
        """
        pass

    def test_get_current_events(self):
        """Test case for get_current_events

        get all current events  # noqa: E501
        """
        pass

    def test_get_event_by_id(self):
        """Test case for get_event_by_id

        Find event by ID  # noqa: E501
        """
        pass

    def test_get_events_by_name(self):
        """Test case for get_events_by_name

        Find events by name  # noqa: E501
        """
        pass

    def test_get_events_by_year(self):
        """Test case for get_events_by_year

        find events by year  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
