# coding: utf-8

"""
    Sommerblut-Database

    Event and festival info  # noqa: E501

    OpenAPI spec version: 1.5.0
    Contact: support@xtain.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sb_db
from sb_db.api.accessibilities_api import AccessibilitiesApi  # noqa: E501
from sb_db.rest import ApiException


class TestAccessibilitiesApi(unittest.TestCase):
    """AccessibilitiesApi unit test stubs"""

    def setUp(self):
        self.api = AccessibilitiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_accessibility_by_id(self):
        """Test case for get_accessibility_by_id

        Find accessibility by ID  # noqa: E501
        """
        pass

    def test_get_all_accessibilities(self):
        """Test case for get_all_accessibilities

        get all accessibilities  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
