# coding: utf-8

"""
    Sommerblut-Database

    Event and festival info  # noqa: E501

    OpenAPI spec version: 1.5.0
    Contact: support@xtain.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sb_db
from sb_db.models.event_price_handling import EventPriceHandling  # noqa: E501
from sb_db.rest import ApiException


class TestEventPriceHandling(unittest.TestCase):
    """EventPriceHandling unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEventPriceHandling(self):
        """Test EventPriceHandling"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sb_db.models.event_price_handling.EventPriceHandling()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
