# coding: utf-8

"""
    Sommerblut-Database

    Event and festival info  # noqa: E501

    OpenAPI spec version: 1.5.0
    Contact: support@xtain.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sb_db
from sb_db.api.locations_api import LocationsApi  # noqa: E501
from sb_db.rest import ApiException


class TestLocationsApi(unittest.TestCase):
    """LocationsApi unit test stubs"""

    def setUp(self):
        self.api = LocationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_current_location_groups(self):
        """Test case for get_all_current_location_groups

        get all locationsGroups from current events  # noqa: E501
        """
        pass

    def test_get_all_location_groups(self):
        """Test case for get_all_location_groups

        get all locationGroups  # noqa: E501
        """
        pass

    def test_get_location_group_by_id(self):
        """Test case for get_location_group_by_id

        Find locationGroup by ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
