# coding: utf-8

"""
    Sommerblut-Database

    Event and festival info  # noqa: E501

    OpenAPI spec version: 1.5.0
    Contact: support@xtain.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sb_db
from sb_db.api.categories_api import CategoriesApi  # noqa: E501
from sb_db.rest import ApiException


class TestCategoriesApi(unittest.TestCase):
    """CategoriesApi unit test stubs"""

    def setUp(self):
        self.api = CategoriesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_categories(self):
        """Test case for get_all_categories

        get all categories  # noqa: E501
        """
        pass

    def test_get_all_current_categories(self):
        """Test case for get_all_current_categories

        get all current categories  # noqa: E501
        """
        pass

    def test_get_category_by_id(self):
        """Test case for get_category_by_id

        Find category by ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
