# coding: utf-8

"""
    Sommerblut-Database

    Event and festival info  # noqa: E501

    OpenAPI spec version: 1.5.0
    Contact: support@xtain.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sb_db
from sb_db.api.running_events_api import RunningEventsApi  # noqa: E501
from sb_db.rest import ApiException


class TestRunningEventsApi(unittest.TestCase):
    """RunningEventsApi unit test stubs"""

    def setUp(self):
        self.api = RunningEventsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_next_event_dates(self):
        """Test case for get_all_next_event_dates

        returns all upcoming events  # noqa: E501
        """
        pass

    def test_get_all_next_event_dates_by_event_id(self):
        """Test case for get_all_next_event_dates_by_event_id

        returns all upcoming eventDates for the given eventId  # noqa: E501
        """
        pass

    def test_get_all_running_event_dates(self):
        """Test case for get_all_running_event_dates

        returns all running eventsDates  # noqa: E501
        """
        pass

    def test_get_all_running_event_dates_by_event_id(self):
        """Test case for get_all_running_event_dates_by_event_id

        returns all running eventDates for the given eventId  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
