# coding: utf-8

"""
    Sommerblut-Database

    Event and festival info  # noqa: E501

    OpenAPI spec version: 1.5.0
    Contact: support@xtain.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sb_db
from sb_db.api.festivals_api import FestivalsApi  # noqa: E501
from sb_db.rest import ApiException


class TestFestivalsApi(unittest.TestCase):
    """FestivalsApi unit test stubs"""

    def setUp(self):
        self.api = FestivalsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_festival_years(self):
        """Test case for get_all_festival_years

        get all festival years  # noqa: E501
        """
        pass

    def test_get_all_festivals(self):
        """Test case for get_all_festivals

        get all festivals  # noqa: E501
        """
        pass

    def test_get_festival_by_id(self):
        """Test case for get_festival_by_id

        find festival by ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
