# coding: utf-8

"""
    Sommerblut-Database

    Event and festival info  # noqa: E501

    OpenAPI spec version: 1.5.0
    Contact: support@xtain.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sb_db
from sb_db.api.tags_api import TagsApi  # noqa: E501
from sb_db.rest import ApiException


class TestTagsApi(unittest.TestCase):
    """TagsApi unit test stubs"""

    def setUp(self):
        self.api = TagsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_tags(self):
        """Test case for get_all_tags

        get all tags  # noqa: E501
        """
        pass

    def test_get_tag_by_id(self):
        """Test case for get_tag_by_id

        Find tag by ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
