# coding: utf-8

"""
    Sommerblut-Database

    Event and festival info  # noqa: E501

    OpenAPI spec version: 1.5.0
    Contact: support@xtain.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sb_db
from sb_db.api.running_streams_api import RunningStreamsApi  # noqa: E501
from sb_db.rest import ApiException


class TestRunningStreamsApi(unittest.TestCase):
    """RunningStreamsApi unit test stubs"""

    def setUp(self):
        self.api = RunningStreamsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_next_streams(self):
        """Test case for get_all_next_streams

        returns all upcoming streams  # noqa: E501
        """
        pass

    def test_get_all_next_streams_by_event_id(self):
        """Test case for get_all_next_streams_by_event_id

        returns all upcoming streams for the given eventId  # noqa: E501
        """
        pass

    def test_get_all_running_streams(self):
        """Test case for get_all_running_streams

        returns all running streams  # noqa: E501
        """
        pass

    def test_get_all_running_streams_by_event_id(self):
        """Test case for get_all_running_streams_by_event_id

        returns all running streams for the given eventId  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
