# coding: utf-8

"""
    Sommerblut-Database

    Event and festival info  # noqa: E501

    OpenAPI spec version: 1.5.0
    Contact: support@xtain.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sb_db
from sb_db.api.dates_of_events_api import DatesOfEventsApi  # noqa: E501
from sb_db.rest import ApiException


class TestDatesOfEventsApi(unittest.TestCase):
    """DatesOfEventsApi unit test stubs"""

    def setUp(self):
        self.api = DatesOfEventsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_dates_of_events(self):
        """Test case for get_all_dates_of_events

        get all dates of events  # noqa: E501
        """
        pass

    def test_get_dates_of_events_by_year(self):
        """Test case for get_dates_of_events_by_year

        find dates of events by year  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
