# coding: utf-8

"""
    Sommerblut-Database

    Event and festival info  # noqa: E501

    OpenAPI spec version: 1.5.0
    Contact: support@xtain.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sb_db
from sb_db.api.stages_api import StagesApi  # noqa: E501
from sb_db.rest import ApiException


class TestStagesApi(unittest.TestCase):
    """StagesApi unit test stubs"""

    def setUp(self):
        self.api = StagesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_current_locations(self):
        """Test case for get_all_current_locations

        get all locations from current events  # noqa: E501
        """
        pass

    def test_get_all_locations(self):
        """Test case for get_all_locations

        get all locations  # noqa: E501
        """
        pass

    def test_get_location_by_id(self):
        """Test case for get_location_by_id

        Find location by ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
